//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestprogRandomWords.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\mikesave")]
        public string UserOption1
        {
            get
            {
                return ((string)(this["UserOption1"]));
            }
            set
            {
                this["UserOption1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\miketest")]
        public string UserOption2
        {
            get
            {
                return ((string)(this["UserOption2"]));
            }
            set
            {
                this["UserOption2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveFormLocationsOnExit
        {
            get
            {
                return ((bool)(this["SaveFormLocationsOnExit"]));
            }
            set
            {
                this["SaveFormLocationsOnExit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("First")]
        public string UserOption4
        {
            get
            {
                return ((string)(this["UserOption4"]));
            }
            set
            {
                this["UserOption4"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormHeight
        {
            get
            {
                return ((int)(this["MainFormHeight"]));
            }
            set
            {
                this["MainFormHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormWidth
        {
            get
            {
                return ((int)(this["MainFormWidth"]));
            }
            set
            {
                this["MainFormWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormX
        {
            get
            {
                return ((int)(this["MainFormX"]));
            }
            set
            {
                this["MainFormX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormY
        {
            get
            {
                return ((int)(this["MainFormY"]));
            }
            set
            {
                this["MainFormY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageLogHeight
        {
            get
            {
                return ((int)(this["MessageLogHeight"]));
            }
            set
            {
                this["MessageLogHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageLogWidth
        {
            get
            {
                return ((int)(this["MessageLogWidth"]));
            }
            set
            {
                this["MessageLogWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageLogX
        {
            get
            {
                return ((int)(this["MessageLogX"]));
            }
            set
            {
                this["MessageLogX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageLogY
        {
            get
            {
                return ((int)(this["MessageLogY"]));
            }
            set
            {
                this["MessageLogY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int MessageLogDefaultHeight
        {
            get
            {
                return ((int)(this["MessageLogDefaultHeight"]));
            }
            set
            {
                this["MessageLogDefaultHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("570")]
        public int MessageLogDefaultWidth
        {
            get
            {
                return ((int)(this["MessageLogDefaultWidth"]));
            }
            set
            {
                this["MessageLogDefaultWidth"] = value;
            }
        }
    }
}
